/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface BebopPartnerInterface extends Interface {
  getFunction(
    nameOrSignature: "partners" | "registerPartner"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "partners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPartner",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "partners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerPartner",
    data: BytesLike
  ): Result;
}

export interface BebopPartner extends BaseContract {
  connect(runner?: ContractRunner | null): BebopPartner;
  waitForDeployment(): Promise<this>;

  interface: BebopPartnerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  partners: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, boolean] & {
        fee: bigint;
        beneficiary: string;
        registered: boolean;
      }
    ],
    "view"
  >;

  registerPartner: TypedContractMethod<
    [partnerId: BigNumberish, fee: BigNumberish, beneficiary: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "partners"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, boolean] & {
        fee: bigint;
        beneficiary: string;
        registered: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerPartner"
  ): TypedContractMethod<
    [partnerId: BigNumberish, fee: BigNumberish, beneficiary: AddressLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
