/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Order {
  export type AggregateStruct = {
    expiry: BigNumberish;
    taker_address: AddressLike;
    maker_addresses: AddressLike[];
    maker_nonces: BigNumberish[];
    taker_tokens: AddressLike[][];
    maker_tokens: AddressLike[][];
    taker_amounts: BigNumberish[][];
    maker_amounts: BigNumberish[][];
    receiver: AddressLike;
    commands: BytesLike;
    flags: BigNumberish;
  };

  export type AggregateStructOutput = [
    expiry: bigint,
    taker_address: string,
    maker_addresses: string[],
    maker_nonces: bigint[],
    taker_tokens: string[][],
    maker_tokens: string[][],
    taker_amounts: bigint[][],
    maker_amounts: bigint[][],
    receiver: string,
    commands: string,
    flags: bigint
  ] & {
    expiry: bigint;
    taker_address: string;
    maker_addresses: string[];
    maker_nonces: bigint[];
    taker_tokens: string[][];
    maker_tokens: string[][];
    taker_amounts: bigint[][];
    maker_amounts: bigint[][];
    receiver: string;
    commands: string;
    flags: bigint;
  };

  export type SingleStruct = {
    expiry: BigNumberish;
    taker_address: AddressLike;
    maker_address: AddressLike;
    maker_nonce: BigNumberish;
    taker_token: AddressLike;
    maker_token: AddressLike;
    taker_amount: BigNumberish;
    maker_amount: BigNumberish;
    receiver: AddressLike;
    packed_commands: BigNumberish;
    flags: BigNumberish;
  };

  export type SingleStructOutput = [
    expiry: bigint,
    taker_address: string,
    maker_address: string,
    maker_nonce: bigint,
    taker_token: string,
    maker_token: string,
    taker_amount: bigint,
    maker_amount: bigint,
    receiver: string,
    packed_commands: bigint,
    flags: bigint
  ] & {
    expiry: bigint;
    taker_address: string;
    maker_address: string;
    maker_nonce: bigint;
    taker_token: string;
    maker_token: string;
    taker_amount: bigint;
    maker_amount: bigint;
    receiver: string;
    packed_commands: bigint;
    flags: bigint;
  };
}

export declare namespace Signature {
  export type MakerSignatureStruct = {
    signatureBytes: BytesLike;
    flags: BigNumberish;
  };

  export type MakerSignatureStructOutput = [
    signatureBytes: string,
    flags: bigint
  ] & { signatureBytes: string; flags: bigint };

  export type PermitSignatureStruct = {
    signatureBytes: BytesLike;
    deadline: BigNumberish;
  };

  export type PermitSignatureStructOutput = [
    signatureBytes: string,
    deadline: bigint
  ] & { signatureBytes: string; deadline: bigint };

  export type Permit2SignatureStruct = {
    signatureBytes: BytesLike;
    deadline: BigNumberish;
    nonce: BigNumberish;
  };

  export type Permit2SignatureStructOutput = [
    signatureBytes: string,
    deadline: bigint,
    nonce: bigint
  ] & { signatureBytes: string; deadline: bigint; nonce: bigint };
}

export declare namespace Transfer {
  export type OldSingleQuoteStruct = {
    useOldAmount: boolean;
    makerAmount: BigNumberish;
    makerNonce: BigNumberish;
  };

  export type OldSingleQuoteStructOutput = [
    useOldAmount: boolean,
    makerAmount: bigint,
    makerNonce: bigint
  ] & { useOldAmount: boolean; makerAmount: bigint; makerNonce: bigint };
}

export interface BebopSettlementInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DOMAIN_SEPARATOR"
      | "hashAggregateOrder"
      | "hashSingleOrder"
      | "partners"
      | "registerAllowedOrderSigner"
      | "registerPartner"
      | "settleSingle"
      | "settleSingleAndSignPermit"
      | "settleSingleAndSignPermit2"
      | "swapSingle"
      | "swapSingleFromContract"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "BebopOrder" | "OrderSignerRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DOMAIN_SEPARATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hashAggregateOrder",
    values: [
      Order.AggregateStruct,
      BigNumberish,
      BigNumberish[][],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "hashSingleOrder",
    values: [Order.SingleStruct, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "partners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAllowedOrderSigner",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPartner",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleSingle",
    values: [
      Order.SingleStruct,
      Signature.MakerSignatureStruct,
      BigNumberish,
      Transfer.OldSingleQuoteStruct,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "settleSingleAndSignPermit",
    values: [
      Order.SingleStruct,
      Signature.MakerSignatureStruct,
      BigNumberish,
      Transfer.OldSingleQuoteStruct,
      BytesLike,
      Signature.PermitSignatureStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "settleSingleAndSignPermit2",
    values: [
      Order.SingleStruct,
      Signature.MakerSignatureStruct,
      BigNumberish,
      Transfer.OldSingleQuoteStruct,
      BytesLike,
      Signature.Permit2SignatureStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapSingle",
    values: [Order.SingleStruct, Signature.MakerSignatureStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapSingleFromContract",
    values: [Order.SingleStruct, Signature.MakerSignatureStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "DOMAIN_SEPARATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashAggregateOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashSingleOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "partners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAllowedOrderSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerPartner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleSingle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleSingleAndSignPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleSingleAndSignPermit2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapSingle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapSingleFromContract",
    data: BytesLike
  ): Result;
}

export namespace BebopOrderEvent {
  export type InputTuple = [eventId: BigNumberish];
  export type OutputTuple = [eventId: bigint];
  export interface OutputObject {
    eventId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderSignerRegisteredEvent {
  export type InputTuple = [
    maker: AddressLike,
    signer: AddressLike,
    allowed: boolean
  ];
  export type OutputTuple = [maker: string, signer: string, allowed: boolean];
  export interface OutputObject {
    maker: string;
    signer: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BebopSettlement extends BaseContract {
  connect(runner?: ContractRunner | null): BebopSettlement;
  waitForDeployment(): Promise<this>;

  interface: BebopSettlementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DOMAIN_SEPARATOR: TypedContractMethod<[], [string], "view">;

  hashAggregateOrder: TypedContractMethod<
    [
      order: Order.AggregateStruct,
      partnerId: BigNumberish,
      updatedMakerAmounts: BigNumberish[][],
      updatedMakerNonces: BigNumberish[]
    ],
    [string],
    "view"
  >;

  hashSingleOrder: TypedContractMethod<
    [
      order: Order.SingleStruct,
      partnerId: BigNumberish,
      updatedMakerAmount: BigNumberish,
      updatedMakerNonce: BigNumberish
    ],
    [string],
    "view"
  >;

  partners: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, boolean] & {
        fee: bigint;
        beneficiary: string;
        registered: boolean;
      }
    ],
    "view"
  >;

  registerAllowedOrderSigner: TypedContractMethod<
    [signer: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  registerPartner: TypedContractMethod<
    [partnerId: BigNumberish, fee: BigNumberish, beneficiary: AddressLike],
    [void],
    "nonpayable"
  >;

  settleSingle: TypedContractMethod<
    [
      order: Order.SingleStruct,
      makerSignature: Signature.MakerSignatureStruct,
      filledTakerAmount: BigNumberish,
      takerQuoteInfo: Transfer.OldSingleQuoteStruct,
      takerSignature: BytesLike
    ],
    [void],
    "payable"
  >;

  settleSingleAndSignPermit: TypedContractMethod<
    [
      order: Order.SingleStruct,
      makerSignature: Signature.MakerSignatureStruct,
      filledTakerAmount: BigNumberish,
      takerQuoteInfo: Transfer.OldSingleQuoteStruct,
      takerSignature: BytesLike,
      takerPermitSignature: Signature.PermitSignatureStruct
    ],
    [void],
    "payable"
  >;

  settleSingleAndSignPermit2: TypedContractMethod<
    [
      order: Order.SingleStruct,
      makerSignature: Signature.MakerSignatureStruct,
      filledTakerAmount: BigNumberish,
      takerQuoteInfo: Transfer.OldSingleQuoteStruct,
      takerSignature: BytesLike,
      takerPermit2Signature: Signature.Permit2SignatureStruct
    ],
    [void],
    "payable"
  >;

  swapSingle: TypedContractMethod<
    [
      order: Order.SingleStruct,
      makerSignature: Signature.MakerSignatureStruct,
      filledTakerAmount: BigNumberish
    ],
    [void],
    "payable"
  >;

  swapSingleFromContract: TypedContractMethod<
    [order: Order.SingleStruct, makerSignature: Signature.MakerSignatureStruct],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DOMAIN_SEPARATOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hashAggregateOrder"
  ): TypedContractMethod<
    [
      order: Order.AggregateStruct,
      partnerId: BigNumberish,
      updatedMakerAmounts: BigNumberish[][],
      updatedMakerNonces: BigNumberish[]
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashSingleOrder"
  ): TypedContractMethod<
    [
      order: Order.SingleStruct,
      partnerId: BigNumberish,
      updatedMakerAmount: BigNumberish,
      updatedMakerNonce: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "partners"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, boolean] & {
        fee: bigint;
        beneficiary: string;
        registered: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerAllowedOrderSigner"
  ): TypedContractMethod<
    [signer: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerPartner"
  ): TypedContractMethod<
    [partnerId: BigNumberish, fee: BigNumberish, beneficiary: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleSingle"
  ): TypedContractMethod<
    [
      order: Order.SingleStruct,
      makerSignature: Signature.MakerSignatureStruct,
      filledTakerAmount: BigNumberish,
      takerQuoteInfo: Transfer.OldSingleQuoteStruct,
      takerSignature: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "settleSingleAndSignPermit"
  ): TypedContractMethod<
    [
      order: Order.SingleStruct,
      makerSignature: Signature.MakerSignatureStruct,
      filledTakerAmount: BigNumberish,
      takerQuoteInfo: Transfer.OldSingleQuoteStruct,
      takerSignature: BytesLike,
      takerPermitSignature: Signature.PermitSignatureStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "settleSingleAndSignPermit2"
  ): TypedContractMethod<
    [
      order: Order.SingleStruct,
      makerSignature: Signature.MakerSignatureStruct,
      filledTakerAmount: BigNumberish,
      takerQuoteInfo: Transfer.OldSingleQuoteStruct,
      takerSignature: BytesLike,
      takerPermit2Signature: Signature.Permit2SignatureStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "swapSingle"
  ): TypedContractMethod<
    [
      order: Order.SingleStruct,
      makerSignature: Signature.MakerSignatureStruct,
      filledTakerAmount: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "swapSingleFromContract"
  ): TypedContractMethod<
    [order: Order.SingleStruct, makerSignature: Signature.MakerSignatureStruct],
    [void],
    "payable"
  >;

  getEvent(
    key: "BebopOrder"
  ): TypedContractEvent<
    BebopOrderEvent.InputTuple,
    BebopOrderEvent.OutputTuple,
    BebopOrderEvent.OutputObject
  >;
  getEvent(
    key: "OrderSignerRegistered"
  ): TypedContractEvent<
    OrderSignerRegisteredEvent.InputTuple,
    OrderSignerRegisteredEvent.OutputTuple,
    OrderSignerRegisteredEvent.OutputObject
  >;

  filters: {
    "BebopOrder(uint128)": TypedContractEvent<
      BebopOrderEvent.InputTuple,
      BebopOrderEvent.OutputTuple,
      BebopOrderEvent.OutputObject
    >;
    BebopOrder: TypedContractEvent<
      BebopOrderEvent.InputTuple,
      BebopOrderEvent.OutputTuple,
      BebopOrderEvent.OutputObject
    >;

    "OrderSignerRegistered(address,address,bool)": TypedContractEvent<
      OrderSignerRegisteredEvent.InputTuple,
      OrderSignerRegisteredEvent.OutputTuple,
      OrderSignerRegisteredEvent.OutputObject
    >;
    OrderSignerRegistered: TypedContractEvent<
      OrderSignerRegisteredEvent.InputTuple,
      OrderSignerRegisteredEvent.OutputTuple,
      OrderSignerRegisteredEvent.OutputObject
    >;
  };
}
