/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Order {
  export type SingleStruct = {
    expiry: BigNumberish;
    taker_address: AddressLike;
    maker_address: AddressLike;
    maker_nonce: BigNumberish;
    taker_token: AddressLike;
    maker_token: AddressLike;
    taker_amount: BigNumberish;
    maker_amount: BigNumberish;
    receiver: AddressLike;
    packed_commands: BigNumberish;
    flags: BigNumberish;
  };

  export type SingleStructOutput = [
    expiry: bigint,
    taker_address: string,
    maker_address: string,
    maker_nonce: bigint,
    taker_token: string,
    maker_token: string,
    taker_amount: bigint,
    maker_amount: bigint,
    receiver: string,
    packed_commands: bigint,
    flags: bigint
  ] & {
    expiry: bigint;
    taker_address: string;
    maker_address: string;
    maker_nonce: bigint;
    taker_token: string;
    maker_token: string;
    taker_amount: bigint;
    maker_amount: bigint;
    receiver: string;
    packed_commands: bigint;
    flags: bigint;
  };
}

export declare namespace Signature {
  export type MakerSignatureStruct = {
    signatureBytes: BytesLike;
    flags: BigNumberish;
  };

  export type MakerSignatureStructOutput = [
    signatureBytes: string,
    flags: bigint
  ] & { signatureBytes: string; flags: bigint };

  export type PermitSignatureStruct = {
    signatureBytes: BytesLike;
    deadline: BigNumberish;
  };

  export type PermitSignatureStructOutput = [
    signatureBytes: string,
    deadline: bigint
  ] & { signatureBytes: string; deadline: bigint };

  export type Permit2SignatureStruct = {
    signatureBytes: BytesLike;
    deadline: BigNumberish;
    nonce: BigNumberish;
  };

  export type Permit2SignatureStructOutput = [
    signatureBytes: string,
    deadline: bigint,
    nonce: bigint
  ] & { signatureBytes: string; deadline: bigint; nonce: bigint };
}

export declare namespace Transfer {
  export type OldSingleQuoteStruct = {
    useOldAmount: boolean;
    makerAmount: BigNumberish;
    makerNonce: BigNumberish;
  };

  export type OldSingleQuoteStructOutput = [
    useOldAmount: boolean,
    makerAmount: bigint,
    makerNonce: bigint
  ] & { useOldAmount: boolean; makerAmount: bigint; makerNonce: bigint };
}

export interface IBebopSettlementInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "settleSingle"
      | "settleSingleAndSignPermit"
      | "settleSingleAndSignPermit2"
      | "swapSingle"
      | "swapSingleFromContract"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "BebopOrder"): EventFragment;

  encodeFunctionData(
    functionFragment: "settleSingle",
    values: [
      Order.SingleStruct,
      Signature.MakerSignatureStruct,
      BigNumberish,
      Transfer.OldSingleQuoteStruct,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "settleSingleAndSignPermit",
    values: [
      Order.SingleStruct,
      Signature.MakerSignatureStruct,
      BigNumberish,
      Transfer.OldSingleQuoteStruct,
      BytesLike,
      Signature.PermitSignatureStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "settleSingleAndSignPermit2",
    values: [
      Order.SingleStruct,
      Signature.MakerSignatureStruct,
      BigNumberish,
      Transfer.OldSingleQuoteStruct,
      BytesLike,
      Signature.Permit2SignatureStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapSingle",
    values: [Order.SingleStruct, Signature.MakerSignatureStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapSingleFromContract",
    values: [Order.SingleStruct, Signature.MakerSignatureStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "settleSingle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleSingleAndSignPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleSingleAndSignPermit2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapSingle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapSingleFromContract",
    data: BytesLike
  ): Result;
}

export namespace BebopOrderEvent {
  export type InputTuple = [eventId: BigNumberish];
  export type OutputTuple = [eventId: bigint];
  export interface OutputObject {
    eventId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IBebopSettlement extends BaseContract {
  connect(runner?: ContractRunner | null): IBebopSettlement;
  waitForDeployment(): Promise<this>;

  interface: IBebopSettlementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  settleSingle: TypedContractMethod<
    [
      order: Order.SingleStruct,
      makerSignature: Signature.MakerSignatureStruct,
      filledTakerAmount: BigNumberish,
      takerQuoteInfo: Transfer.OldSingleQuoteStruct,
      takerSignature: BytesLike
    ],
    [void],
    "payable"
  >;

  settleSingleAndSignPermit: TypedContractMethod<
    [
      order: Order.SingleStruct,
      makerSignature: Signature.MakerSignatureStruct,
      filledTakerAmount: BigNumberish,
      takerQuoteInfo: Transfer.OldSingleQuoteStruct,
      takerSignature: BytesLike,
      takerPermitSignature: Signature.PermitSignatureStruct
    ],
    [void],
    "payable"
  >;

  settleSingleAndSignPermit2: TypedContractMethod<
    [
      order: Order.SingleStruct,
      makerSignature: Signature.MakerSignatureStruct,
      filledTakerAmount: BigNumberish,
      takerQuoteInfo: Transfer.OldSingleQuoteStruct,
      takerSignature: BytesLike,
      takerPermit2Signature: Signature.Permit2SignatureStruct
    ],
    [void],
    "payable"
  >;

  swapSingle: TypedContractMethod<
    [
      order: Order.SingleStruct,
      makerSignature: Signature.MakerSignatureStruct,
      filledTakerAmount: BigNumberish
    ],
    [void],
    "payable"
  >;

  swapSingleFromContract: TypedContractMethod<
    [order: Order.SingleStruct, makerSignature: Signature.MakerSignatureStruct],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "settleSingle"
  ): TypedContractMethod<
    [
      order: Order.SingleStruct,
      makerSignature: Signature.MakerSignatureStruct,
      filledTakerAmount: BigNumberish,
      takerQuoteInfo: Transfer.OldSingleQuoteStruct,
      takerSignature: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "settleSingleAndSignPermit"
  ): TypedContractMethod<
    [
      order: Order.SingleStruct,
      makerSignature: Signature.MakerSignatureStruct,
      filledTakerAmount: BigNumberish,
      takerQuoteInfo: Transfer.OldSingleQuoteStruct,
      takerSignature: BytesLike,
      takerPermitSignature: Signature.PermitSignatureStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "settleSingleAndSignPermit2"
  ): TypedContractMethod<
    [
      order: Order.SingleStruct,
      makerSignature: Signature.MakerSignatureStruct,
      filledTakerAmount: BigNumberish,
      takerQuoteInfo: Transfer.OldSingleQuoteStruct,
      takerSignature: BytesLike,
      takerPermit2Signature: Signature.Permit2SignatureStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "swapSingle"
  ): TypedContractMethod<
    [
      order: Order.SingleStruct,
      makerSignature: Signature.MakerSignatureStruct,
      filledTakerAmount: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "swapSingleFromContract"
  ): TypedContractMethod<
    [order: Order.SingleStruct, makerSignature: Signature.MakerSignatureStruct],
    [void],
    "payable"
  >;

  getEvent(
    key: "BebopOrder"
  ): TypedContractEvent<
    BebopOrderEvent.InputTuple,
    BebopOrderEvent.OutputTuple,
    BebopOrderEvent.OutputObject
  >;

  filters: {
    "BebopOrder(uint128)": TypedContractEvent<
      BebopOrderEvent.InputTuple,
      BebopOrderEvent.OutputTuple,
      BebopOrderEvent.OutputObject
    >;
    BebopOrder: TypedContractEvent<
      BebopOrderEvent.InputTuple,
      BebopOrderEvent.OutputTuple,
      BebopOrderEvent.OutputObject
    >;
  };
}
