/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IPermit2 {
  export type PermitDetailsStruct = {
    token: AddressLike;
    amount: BigNumberish;
    expiration: BigNumberish;
    nonce: BigNumberish;
  };

  export type PermitDetailsStructOutput = [
    token: string,
    amount: bigint,
    expiration: bigint,
    nonce: bigint
  ] & { token: string; amount: bigint; expiration: bigint; nonce: bigint };

  export type PermitBatchStruct = {
    details: IPermit2.PermitDetailsStruct[];
    spender: AddressLike;
    sigDeadline: BigNumberish;
  };

  export type PermitBatchStructOutput = [
    details: IPermit2.PermitDetailsStructOutput[],
    spender: string,
    sigDeadline: bigint
  ] & {
    details: IPermit2.PermitDetailsStructOutput[];
    spender: string;
    sigDeadline: bigint;
  };

  export type AllowanceTransferDetailsStruct = {
    from: AddressLike;
    to: AddressLike;
    amount: BigNumberish;
    token: AddressLike;
  };

  export type AllowanceTransferDetailsStructOutput = [
    from: string,
    to: string,
    amount: bigint,
    token: string
  ] & { from: string; to: string; amount: bigint; token: string };
}

export interface IPermit2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowance"
      | "permit"
      | "transferFrom((address,address,uint160,address)[])"
      | "transferFrom(address,address,uint160,address)"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "permit",
    values: [AddressLike, IPermit2.PermitBatchStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom((address,address,uint160,address)[])",
    values: [IPermit2.AllowanceTransferDetailsStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom(address,address,uint160,address)",
    values: [AddressLike, AddressLike, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "permit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom((address,address,uint160,address)[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom(address,address,uint160,address)",
    data: BytesLike
  ): Result;
}

export interface IPermit2 extends BaseContract {
  connect(runner?: ContractRunner | null): IPermit2;
  waitForDeployment(): Promise<this>;

  interface: IPermit2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowance: TypedContractMethod<
    [user: AddressLike, token: AddressLike, spender: AddressLike],
    [
      [bigint, bigint, bigint] & {
        amount: bigint;
        expiration: bigint;
        nonce: bigint;
      }
    ],
    "view"
  >;

  permit: TypedContractMethod<
    [
      owner: AddressLike,
      permitBatch: IPermit2.PermitBatchStruct,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  "transferFrom((address,address,uint160,address)[])": TypedContractMethod<
    [transferDetails: IPermit2.AllowanceTransferDetailsStruct[]],
    [void],
    "nonpayable"
  >;

  "transferFrom(address,address,uint160,address)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      token: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [user: AddressLike, token: AddressLike, spender: AddressLike],
    [
      [bigint, bigint, bigint] & {
        amount: bigint;
        expiration: bigint;
        nonce: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "permit"
  ): TypedContractMethod<
    [
      owner: AddressLike,
      permitBatch: IPermit2.PermitBatchStruct,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom((address,address,uint160,address)[])"
  ): TypedContractMethod<
    [transferDetails: IPermit2.AllowanceTransferDetailsStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom(address,address,uint160,address)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      token: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
